### ISSUE TITLE
Remove files after upload

### ISSUE THREAD

**Issue by baskevin** [pqina/ngx-filepond#13]
Hello 

I tried since 1 day try to remove allready uploaded files. 

I treid with 

`this.myPond.removeFile();`
- this just remove the first file in the pond and only when upload is finished
- im also not able to read the id from the file which is uploaded even my server returns an id. 

also this are my pond options 

```js
    pondOptions = {
        class: 'my-filepond',
        multiple: true,
        labelIdle: 'Drop files here',
        instantUpload: true,
        server: {
            url: 'http://localhost/exxas/api',
            process: (fieldName, file, metadata, load, error, progress, abort) => {


                const request = new XMLHttpRequest();
                request.open('POST', 'http://localhost/api/proxy/upload');

                request.upload.onprogress = (e) => {
                    progress(e.lengthComputable, e.loaded, e.total);
                };

                request.onload = () => {
                    if (request.status >= 200 && request.status < 300) {
                        load(request.responseText);

                    } else {
                        // Can call the error method if something is wrong, should exit after
                        error('oh no');
                    }
                };

                request.send(formData);

                return {
                    abort: () => {
                        request.abort();
                        abort();
                    }
                };
            },
            revert: './revert.php',
            restore: './restore.php?id=',
            fetch: './fetch.php?data='
        },
    };
```

Does anybody have an approach to delete allready uploaded files in filepond? 

Thanks in advance. 

Kind regards

**Comment by baskevin** [comment]
It also seems that the callback `onprocessfiles` doesn't work

**Comment by Damian710** [comment]
The processMethod has to return the filedName in order for the revert to work

**Comment by aullah** [comment]
I can also confirm that `onprocessfile` (non-plural) doesn't work either; the event doesn't get triggered, whereas in my code if I were to replace `onprocessfile` with `addfile` the function does execute when uploading a file.

This indicates that it isn't a problem with my code but the `onprocessfile` method.

I haven't integrated in with any front-end framework and I'm using vanilla JS.

**Comment by Danand3** [comment]
Hi @baskevin did you find a solution for this?

**Comment by rikschennink** [comment]
If someone can create a reproduction I'm happy to take a look. 

Can fork this demo: https://stackblitz.com/github/pqina/pintura-example-angular
