### ISSUE TITLE
Working project

### ISSUE THREAD

**Issue by ronaldohoch** [pqina/ngx-filepond#17]
Hello!

Could you show a project with working code or code snippets?
I am not getting the form to be sent, I am using ReactiveFormModule to send it, but it is empty.

FilePond does not return the submitted image id and also does not send anything when deleting an image, it ends up being an empty DELETE for the API.

Can you help me?

**Comment by rikschennink** [comment]
The file object itself is not exposed in a file input field as it's not possible to write to such a field, therefor I imagine you are going to have to supply the files to `ReactiveFormModule` yourself.
