### ISSUE TITLE
Feature request: lazyload

### ISSUE THREAD

**Issue by gogoout** [pqina/ngx-filepond#20]
Hi there, 
First of all, thanks for the amazing project.
Currently filepond is gzipped at around 21k, but for most application, uploading service is not something that needs to be eager loaded. So it would be nice to have a lazyload feature out of the box.

I've managed to get the lazyload feature up and running fine under my branch: https://github.com/gogoout/ngx-filepond/tree/%40feature/lazyload

So instead of include filepond in the vendor, it will create a separate bundle by webpack.
The results are like (in development mode, so unminified):

original:
```
chunk {main} main.js, main.js.map (main) 25.8 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 387 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 770 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 65.8 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.17 MB [initial] [rendered]
```

now:
```
chunk {filepond} filepond.js, filepond.js.map (filepond) 263 kB  [rendered]
chunk {main} main.js, main.js.map (main) 41.2 kB [initial] [rendered]
chunk {plugins} plugins.js, plugins.js.map (plugins) 41.9 kB  [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 387 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 770 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.01 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 65.8 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.87 MB [initial] [rendered]
```

Does this looking good to you?

**Comment by gogoout** [comment]
Seems this https://github.com/ng-packagr/ng-packagr/issues/1285 is prevent me to package it. I guess we have to wait until this is fixed. Meanwhile I will just copy paste the adapter in my own project.
Feel free to close this issue if you wanted.

**Comment by rikschennink** [comment]
You're absolutely right that the logic can probably be lazy loaded. On the [Doka product page](https://pqina.nl/doka/) I'm loading FilePond conditionally using `async import()` so I guess this also shouldn't be an issue on Angular (I'm no expert).

Will close as the problem seems to originate from ng-packagr.
