### ISSUE TITLE
CSV File is missing 

### ISSUE THREAD

**Issue by NSnietol** [pqina/ngx-filepond#24]
Hello fellow developer!

🐜 If you've found a bug, please use the template below to report it.

When we try to attach a csv file, the library isn't able to identify this kind of file.
I've been trying to attach and filter files by application/csv or text/csv, nevertheless, as you can see on the screenshots, it doesn't get the type.

![Evidence1](https://user-images.githubusercontent.com/12100190/75600053-d6877b80-5a78-11ea-8aed-e77fbb9859af.jpg)

**The more details you provide, the more inclined other developers are to help you and the faster the problem is resolved.**

If you think the issue is related FilePond itself and not the Angular framework or adapter, please submit the issue in the FilePond repository.

Please format code snippets using backticks and don't forget to set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

### How to reproduce
Attach any csv file and check the type value.

### Expected behavior

I should see the type in the Object.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / (X) Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
See https://github.com/pqina/filepond-plugin-file-validate-type/issues/2
