### ISSUE TITLE
Does ngx-filepond have support for Angular 9

### ISSUE THREAD

**Issue by smithbrianscott** [pqina/ngx-filepond#30]
Does ngx-filepond have support for Angular 9 yet? We are looking to upgrade to Angular 9 but couldn't find anywhere online if filepond will work there or not.

**Comment by rikschennink** [comment]
Honestly haven't tested yet, do let me know if it causes any trouble.

**Comment by smithbrianscott** [comment]
> Honestly haven't tested yet, do let me know if it causes any trouble.

I am not getting any console errors, but just by adding exists working files that was being used in previous versions of Angular into Angular 9, this is what I see.

![image](https://user-images.githubusercontent.com/19986009/85744785-272f7e00-b6d3-11ea-93e3-b704a7574666.png)

**Comment by rikschennink** [comment]
This looks like the CSS is not being loaded properly, maybe it’s scoping the (global) styles. I’ll try to investigate next week.

**Comment by smithbrianscott** [comment]
> This looks like the CSS is not being loaded properly, maybe it’s scoping the (global) styles. I’ll try to investigate next week.

Geez, I missed it, I am using a new template and forgot to include the css in angular.json ... lol 

Thanks for your prompt assistance!
