### ISSUE TITLE
Patch chunks return undefined

### ISSUE THREAD

**Issue by alenahrenovskaya** [pqina/ngx-filepond#33]
Hello!

What about chunkUploads and patch in server configurations?

My params:
```
  pondOptions = {
    multiple: true,
    labelIdle: 'Нажмите, чтобы добавить файлы или перенести их сюда',
    chunkUploads: true,
    chunkSize: 100000,
    server: {
      url: 'http://localhost:4200/fp/',
      process: {
        url: './process/',
        method: 'POST',
        onload: (response) => response.key,
        onerror: (response) => response.data,
        ondata: (formData) => this.getFormData(formData)
      },
      revert: './revert/',
      restore: './restore/',
      load: './load/',
      fetch: './fetch/',
      patch: './patch/',
      headers: {
        'Authorization': localStorage.getItem('authorization'),
      }
    },
  };
```

But `undefined` is sent to server instead of chunk ID:

![image](https://user-images.githubusercontent.com/35628947/91015855-8555e000-e5f4-11ea-8f2a-0f9f32fc3824.png)

Project Angular version 7.2.1

**Comment by rikschennink** [comment]
I'm not sure, please provide a public test case

**Comment by rezadavari** [comment]
Hello
I have the same problem,
undefined is sent to the server instead of chunk ID

**Comment by rikschennink** [comment]
@rezadavari see earlier response, will close till test case has been provided.

> I'm not sure, please provide a public test case

**Comment by rezadavari** [comment]
> Hello
> I have the same problem,
> undefined is sent to the server instead of chunk ID

I solved my problem like this:

step1: from the server after receiving post request return serverId in the Response body :

           $transferid='abcd123' //for example
            return Response::make($transferid, 200, [
                'Content-Type' => 'text/plain'
            ]);
            
step2: from the client read the returnd id in response body in load section like this:

              onload: (response) => {
                   return response.responseText; 
               }
now the result will be: localhost:1010/?patch=abcd123
or
 if you write a patch section separately  

            patch:{
            ......................
            }

the result will be : localhost:1010/abcd123

and it is working right
