### ISSUE TITLE
error in registerPlugin function when registering Image Preview

### ISSUE THREAD

**Issue by kevduggan** [pqina/ngx-filepond#4]
On Angular CLI: 1.7.4/Angular: 5.2.11

I have added the Image Preview plugin but getting the following error on the console:
<img width="1439" alt="screen shot 2018-06-16 at 21 19 32" src="https://user-images.githubusercontent.com/3285939/41502135-2c90244a-71ab-11e8-878c-40148ec53921.png">

the following is my very basic app module

```import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { FilePondModule, registerPlugin } from 'ngx-filepond';

import FilepondPluginImagePreview from 'filepond-plugin-image-preview';
registerPlugin(FilepondPluginImagePreview);

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FilePondModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { } 
```

**Comment by rikschennink** [comment]
Try  ‘FilePond’ instead of ‘Filepond’

**Comment by kevduggan** [comment]
thanks @rikschennink, still the same error occuring

**Comment by kevduggan** [comment]
`
import { FilePondModule, registerPlugin } from 'ngx-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
console.log('registerPlugin: ', registerPlugin);
console.log('FilePondPluginFileValidateType: ', FilePondPluginFileValidateType);
`
logs
<img width="1436" alt="screen shot 2018-06-18 at 10 28 59" src="https://user-images.githubusercontent.com/3285939/41528617-79f74c94-72e2-11e8-9a72-35632c9ce013.png">

**Comment by kevduggan** [comment]
got it working using
`
import * as FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import * as FilePondPluginImagePreview from 'filepond-plugin-image-preview';

registerPlugin(FilePondPluginFileValidateType);
registerPlugin(FilePondPluginImagePreview);
`
<img width="556" alt="screen shot 2018-06-18 at 10 50 13" src="https://user-images.githubusercontent.com/3285939/41529551-79e25b9c-72e5-11e8-9128-8e623f274c13.png">
![Uploading Screen Shot 2018-06-18 at 10.50.29.png…]()

**Comment by rikschennink** [comment]
This is so strange, I'm not sure why on some Angular projects you need to write:
```js
import * as FilePondPluginFileValidateType
```
And on others it works just fine when writing 

```js
import FilePondPluginFileValidateType
```

And others require directly referencing the package `.esm` file.

Is this a node/npm version thing? If anyone can shed some light on this, that would be nice :-)

**Comment by kevduggan** [comment]
Ya, it's weird stuff.
That image preview is a work of art though!

**Comment by rikschennink** [comment]
Thanks! :D Glad to hear it's working, enjoy!

**Comment by Masterxilo** [comment]
I also recently upgraded filepond and this plugin's version and had to change
```
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
```
(which now gave me 'error TS1192: Module '"/data/jenkins/workspace/aubsgesuch-ui_feature_npm-update/node_modules/filepond-plugin-image-preview/types/index"' has no default export.

[2022-10-06T09:13:35.948Z] 

[2022-10-06T09:13:35.948Z] 6 import FilePondPluginImagePreview from 'filepond-plugin-image-preview';')

to
```
import * as FilePondPluginImagePreview from 'filepond-plugin-image-preview';
```
