### ISSUE TITLE
Fetching Items on Another Server 

### ISSUE THREAD

**Issue by theandrewdodson** [pqina/ngx-filepond#6]
### Summary

Setting a custom fetch URL for the files object on another server doesn't work as expected

### How to reproduce

I've tried multiple different ways to set the URL properly, here are a few scenarios:

1. Set the server base URL then set the file source in the file object
```js
this.fileOptions.server.url = 'http://otherserver.com/api'
this.thumbnailFiles = [{source: '12345', options: 'local'}];
```
This results in the client code's browser URL being used as the base, in this case localhost

`VM9523:1 GET http://localhost:4200/12345 404 (Not Found)`

2. Set the server base URL to '' then set the source as the complete URL to the image
```js
 filesOptions = {
    acceptedFileTypes: 'application/pdf',
    allowMultiple: false,
    // don't allow revert since we are doing a manual delete
    allowRevert: false,
    labelIdle: 'Drop files here or click to browse',
    server: '',
  };

 this.thumbnailFiles = [{source: 'https://otherserver.com/filename', options: 'local'}];
```
 This sets the client URL then appends the entire source, in this case localhost + source value

3. Set server URL then use entire source URL in the file config

```js
this.fileOptions.server.url = 'http://otherserver.com/api'
this.thumbnailFiles = [{source: 'https://otherserver.com/filename', options: 'local'}];
```
I only include this configuration because the output now includes the server URL unlike 1 but then appends entire URL for source to the end.

I've also tried setting the fetch URL in the FilePond config with the same results.

### Expected behaviour

Fetch + File Source 
https://otherserver.com/filename

**Comment by rikschennink** [comment]
The following examples are based on how the FilePond component is set up in the repository README.


```
http://otherserver.com/api?load=12345
```

```ts

export class AppComponent {

  pondOptions = {
    server: 'http://otherserver.com/api'
  }

  pondFiles = [
    {
      source: '12345',
      options: {
        type: 'local'
      }
    }
  ]
}
```

For all the following examples `pondFiles` is hidden as it stays the same as in the first example.

Using an object with a URL will result in the same URL structure.

```
http://otherserver.com/api?load=12345
```

```ts

export class AppComponent {

  pondOptions = {
    server: {
        url: 'http://otherserver.com/api'
    }
  }

  // pondFiles...
}
```

Replacing the URL in the load component will change the `?load=` part of the request URL.

```
http://otherserver.com/api/load/12345
```

```ts

export class AppComponent {

  pondOptions = {
    server: {
      url: 'http://otherserver.com/api/',
      load: {
        url: 'load/'
      }
    }
  }

  // pondFiles...
}
```

**Comment by theandrewdodson** [comment]
okay, so I was using the wrong action property, thanks!

when would I use fetch? I guess I'm not clear on it's purpose.

**Comment by rikschennink** [comment]
It’s used by FilePond to download remote URLs dropped by the user or added via `addFile`, basically your server fetches the file from the remote server and serves it back to the client circumventing CORS.
