### ISSUE TITLE
TypeError: getNumericAspectRatioFromString is not a function

### ISSUE THREAD

**Issue by realsoftdev** [pqina/ngx-filepond#7]
### Error
```core.js:1449 ERROR Error: Uncaught (in promise): TypeError: getNumericAspectRatioFromString is not a function
TypeError: getNumericAspectRatioFromString is not a function
```

### Summary
// Angular Module

import { FilePondModule, registerPlugin } from "angular-filepond";
import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.esm";
import FilePondPluginImagePreview from "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.esm";
import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.esm";
import FilePondPluginImageResize from "filepond-plugin-image-resize/dist/filepond-plugin-image-resize.esm";
import FilePondPluginImageTransform from "filepond-plugin-image-transform/dist/filepond-plugin-image-transform.esm";
import FilePondPluginImageCrop from "filepond-plugin-image-crop/dist/filepond-plugin-image-crop.esm";

registerPlugin(
    FilePondPluginFileValidateType,
    FilePondPluginImageExifOrientation,
    FilePondPluginImagePreview,
    FilePondPluginImageCrop,
    FilePondPluginImageResize,
    FilePondPluginImageTransform
);

// HTML

<FilePond #LogoUploadFilePond
    acceptedFileTypes="image/png, image/jpeg, image/gif"
    labelIdle='Drag & Drop your picture or <span class="filepond--label-action">Browse</span>'
    imagePreviewHeight=170
    imageCropAspectRatio="1:1"
    imageResizeTargetWidth=200
    imageResizeTargetHeight=200
    stylePanelLayout="compact circle"
    styleLoadIndicatorPosition='center bottom'
    styleProgressIndicatorPosition='right bottom'
    styleButtonRemoveItemPosition='left bottom'
    styleButtonProcessItemPosition='right bottom'
>
</FilePond>

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Device       | Laptop
| Browser      | Chrome 69.0.3497

**Comment by rikschennink** [comment]
Have you updated everything to latest version?

**Comment by rikschennink** [comment]
Never mind, I see I haven't updated the FilePond dependency yet.

**Comment by realsoftdev** [comment]
@rikschennink Thanks, but actually it was fixed, but I can't see upload button after drag or browse new file.

**Comment by rikschennink** [comment]
Judging from your code snippet it seems that you've not yet set up a server therefor it doesn't have a target to upload to.

**Comment by rikschennink** [comment]
Will close as the original issue has been resolved.
