### ISSUE TITLE
[Bug] Can't import FilePondComponent

### ISSUE THREAD

**Issue by eLod** [pqina/ngx-filepond#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated Angular FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

As per an example in the readme trying to use `import { FilePondComponent } from 'ngx-filepond';` generates error ` Error: export 'FilePondComponent' (imported as 'FilePondComponent') was not found in 'ngx-filepond' (possible exports: FilePondModule, registerPlugin, ɵa)`, am i missing something here, sorry if it's something obvious.

### Reproduction

Install and try to import.

### Environment

```markdown
- Device: computer
- OS: macOS 11
- Browser: Chrome 110
- Angular version: 13.0.3
```

**Comment by rikschennink** [comment]
If you checkout the project it works so maybe this is difference in tsconfig.json file?

**Comment by eLod** [comment]
i am not sure if i am missing something, but if by checkout you mean the app component code in git(hub) repository, that one is using a relative import, e.g. [src/app/app.component.ts#L2](https://github.com/pqina/ngx-filepond/blob/master/src/app/app.component.ts#L2) . the problem is with the generated files in node_modules, here is a [stackblitz](https://stackblitz.com/edit/angular-hyyqxk?file=src/main.ts). this is how code looks like in `node_modules/ngx-filepond/ngx-filepond.d.ts`:

```js
/**
 * Generated bundle index. Do not edit.
 */
export * from './public_api';
export { FilePondComponent as ɵa } from './filepond.component';

//# sourceMappingURL=ngx-filepond.d.ts.map
```

**Comment by eLod** [comment]
i think you are just missing an export from https://github.com/pqina/ngx-filepond/blob/master/src/app/modules/filepond/filepond.module.ts#L4 as it is never exported, but i am not very familiar with angular plugin authoring.

**Comment by rikschennink** [comment]
Ah yes, testing.

**Comment by eLod** [comment]
thank you, it works.
