### ISSUE TITLE
[Bug]  onreorderfiles CallBack not working on angular?

### ISSUE THREAD

**Issue by Gabiruti** [pqina/ngx-filepond#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated FilePond and its plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

Im using angular and trying to use onreorderfiles() callback but nothing happens.

my html:
```html
<file-pond
  #myPond
  name='UploadForm[imagem][]'
  [options]="pondOptions"
  (oninit)="pondHandleInit()"
  [files]="pondFiles"
  (onaddfile)="pondHandleAddFile($event)"
  (onactivatefile)="pondHandleActivateFile($event)"
  (onremovefile)="pondHandleRemove($event)"
  (onreorderfiles)="pondHandleReOrder($event)"
/>
```
my func:
```js
pondHandleReOrder(event: any) {
        console.log(event.pond.getFiles(), 'AQUI')

    }
```

### Reproduction

1. create a new angular app
2. setup filepond
3. try to use onreorderfiles callback

### Environment

```markdown
- Device: PC
- OS: Ubuntu 20.04.6 LTS 
- Browser: Chrome Version 120.0.6099.129 64 bits
```

**Comment by rikschennink** [comment]
Just published 7.0.2 of the angular adapter, should solve the issue

**Comment by Gabiruti** [comment]
Now something actually happens, but this error is popping in the console:
![image (2)](https://github.com/pqina/ngx-filepond/assets/61449361/a98d4c3b-35aa-46ea-bc08-986bbdd46ef2)

**Comment by rikschennink** [comment]
Shoot, missed something. 7.0.3 should fix it.

**Comment by Gabiruti** [comment]
Working fine now, thank you very much!
