### ISSUE TITLE
[Feature] Option to use HTTPClient instead of vanilla XHR

### ISSUE THREAD

**Issue by khalic-lab** [pqina/ngx-filepond#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Our install uses MSAL to authorize api calls, via an interceptor. Unfortunately, filepond does not user Angular HTTP to upload , which means there is no Bearer attached to api requests.

### Describe the solution you'd like

Create an option to use Angular's http module instead of the vanilla JS one.

### Describe alternatives you've considered

A complete example with `process: () => {/* use ng http */}` would also work, although not as useful.

**Comment by rikschennink** [comment]
You can pass custom headers to the `server` prop.

https://pqina.nl/filepond/docs/api/server/#object-configuration

```js
{
    server: {
        url: 'http://192.168.0.100',
        process: {
            url: './process',
            method: 'POST',
            withCredentials: false,
            headers: {},
            timeout: 7000,
            onload: null,
            onerror: null,
            ondata: null,
        },
    },
}
```

**Comment by khalic-lab** [comment]
That doesn't solve the maintenance issue, and the interceptor is used for other purposes than the bearer. So this doesn't solve my issue

**Comment by rikschennink** [comment]
You could set up a custom process method and use the HttpClient in there?

https://pqina.nl/filepond/docs/api/server/#process-1
