### ISSUE TITLE
How can I use with HttpInterceptor for adding jwt token?

### ISSUE THREAD

**Issue by geniuz** [pqina/ngx-filepond#9]
How can I use with HttpInterceptor for adding jwt token?
Thanks

**Comment by hamid-riahi** [comment]
I'm having the same problem. The code is in JQuery and it would be nice have an example in Angular

**Comment by xmlking** [comment]
May be this could help

https://github.com/xmlking/ngx-starter-kit/blob/develop/libs/experiments/src/lib/containers/file-upload/file-upload.component.ts
